# https://docs.docker.com/compose/rails/

version: '3'
services:
  db:
    image: postgres
    env_file:
      - ~/.env/myproject/db.env # minimal requirement: POSTGRES_PASSWORD=use-pwgen
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ~/.env/myproject/db.env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db

volumes:
  db-data:
